import Vue from 'vue'
import VueRouter from 'vue-router'

import Login from "./login"
import Register from "./register"

Vue.use(VueRouter);

const router = new VueRouter({
  mode:"hash",
  routes:[
    {
      path:"/",
      redirect:"/home"
    },
    {
      path:"/home",
      component:_=>import("@pages/home"),
      name:"home",
      meta:{
        title:"首页",
        tabBarFlag:true,
        requiredAuth:false
      },
    },
    {
      path:"/classify",
      component:_=>import("@pages/classify"),
      name:"classify",
      meta:{
        title:"分类",
        tabBarFlag:true,
        requiredAuth:false
      },
    },
    {
      path:"/cart",
      component:_=>import("@pages/cart"),
      name:"cart",
      meta:{
        title:"购物车",
        tabBarFlag:false,
        requiredAuth:true
      },
    },
    {
      path:"/mine",
      component:_=>import("@pages/mine"),
      name:"mine",
      meta:{
        title:"我的",
        tabBarFlag:true,
        requiredAuth:true
      },
    },
    {
      path:"/city",
      component:_=>import("@pages/city"),
      name:"city",
      meta:{
        title:"定位",
        tabBarFlag:false,
        requiredAuth:false
      },
    },
    {
      path:"/search",
      component:_=>import("@pages/search"),
      name:"search",
      meta:{
        title:"搜索",
        tabBarFlag:false,
        requiredAuth:false
      },
    },
    {
      path:"/experience",
      component:_=>import("@pages/experience"),
      name:"experience",
      meta:{
        title:"体验馆列表",
        tabBarFlag:false,
        requiredAuth:false
      },
    },
    {
      path:"/hall",
      component:_=>import("@pages/hall"),
      name:"hall",
      meta:{
        title:"品牌体验馆",
        tabBarFlag:false,
        requiredAuth:false
      },
    },
    {
      path:"/esc",
      component:_=>import("@pages/esc"),
      name:"esc",
      meta:{
        title:"个人中心",
        tabBarFlag:false,
        requiredAuth:true
      },
    },
    {
      path:"/logins",
      component:_=>import("@pages/login"),
      name:"logins",
      meta:{
        title:"注册登陆",
        tabBarFlag:false,
        requiredAuth:false,
      },
      children:[
        {
          path:"",
          redirect:"login"
        },
        Login,
        Register
      ]
    },
    {
      path:"/today",
      component:_=>import("@pages/today"),
      name:"today",
    },
    {
      path:"/wood",
      component:_=>import("@pages/wood"),
      name:"wood",
    },
    {
      path:"/storeList",
      component:_=>import("@pages/list"),
      name:"storeList",
    },
    {
      path:"/details/:id",
      component:_=>import("@pages/details"),
      name:"details",

    }
  ]
})


export default router;